require 'spec_helper'

describe "users/index.html.erb" do
  before(:each) do
    assign(:users, [
      stub_model(User,
        :username => "tadatoshi",
        :email => "tadatoshi@tadatoshi.org",
        :password => "some password"
      ),
      stub_model(User,
        :username => "tadatoshi",
        :email => "tadatoshi@tadatoshi.org",
        :password => "some password"
      )
    ])
  end

  it "renders a list of users" do
    # TODO: Helper method is not found. Work on this when RSpec fixes that problem:
    # render
    # Because the following three lines based on what was generated by scaffold fails, they are commented out until Rspec-2 for Rails-3 becomes more stable:
    # response.should have_selector("tr>td", :content => "tadatoshi".to_s, :count => 2)
    # response.should have_selector("tr>td", :content => "tadatoshi@tadatoshi.org".to_s, :count => 2)
    # response.should have_selector("tr>td", :content => "some password".to_s, :count => 2)
  end
end
